In [1]:
import numpy as np
import time
from collections import Counter

import tensorflow as tf

## Book Import, Analysis and Clean up for Network

In [2]:
text = open('data/HPBook1.txt', 'r', encoding = 'utf-8')
text = text.read()
print('Some sample text from the book -->')
text[:1000]

Some sample text from the book -->


"Harry Potter and the Sorcerer's Stone \n\nCHAPTER ONE \n\nTHE BOY WHO LIVED \n\nMr. and Mrs. Dursley, of number four, Privet Drive, were proud to say that they were perfectly normal, thank you very much. They were the last people you'd expect to be involved in anything strange or mysterious, because they just didn't hold with such nonsense. \n\nMr. Dursley was the director of a firm called Grunnings, which made drills. He was a big, beefy man with hardly any neck, although he did have a very large mustache. Mrs. Dursley was thin and blonde and had nearly twice the usual amount of neck, which came in very useful as she spent so much of her time craning over garden fences, spying on the neighbors. The Dursleys had a small son called Dudley and in their opinion there was no finer boy anywhere. \n\nThe Dursleys had everything they wanted, but they also had a secret, and their greatest fear was that somebody would discover it. They didn't think they could bear it if anyone found out about 

In [5]:
total_words = len(text.split())
total_characters = len(text)
unique_words = len(set(text.split()))
unique_characters = len(set(text))
paragraphs = text.split('\n\n')

print ("Total words in book :", total_words)
print ("Total characters in book :", total_characters)
print ("Unique words in book :", unique_words)
print ("Unique characters in book :", unique_characters)
print ("Total Paragraphs :", len(paragraphs))

Total words in book : 78449
Total characters in book : 442744
Unique words in book : 11897
Unique characters in book : 80
Total Paragraphs : 3033


In [6]:
most_words = Counter()
for i in range(len(paragraphs)):
    for x in paragraphs[i]:
        most_words[x] +=1

        
most_words.most_common()

[(' ', 78449),
 ('e', 39628),
 ('t', 27993),
 ('a', 25887),
 ('o', 25809),
 ('n', 21337),
 ('r', 20990),
 ('h', 19535),
 ('i', 19422),
 ('s', 18870),
 ('d', 15932),
 ('l', 14385),
 ('u', 9562),
 ('y', 8293),
 ('g', 8127),
 ('w', 7744),
 ('m', 6729),
 ('f', 6431),
 ('c', 6403),
 ('.', 6136),
 (',', 5658),
 ('b', 4980),
 ('p', 4909),
 ('"', 4747),
 ('k', 3930),
 ("'", 3141),
 ('H', 2996),
 ('v', 2716),
 ('-', 1986),
 ('I', 1393),
 ('T', 1055),
 ('S', 844),
 ('?', 754),
 ('A', 703),
 ('D', 685),
 ('M', 665),
 ('R', 660),
 ('W', 653),
 ('P', 639),
 ('G', 492),
 ('N', 488),
 ('!', 474),
 ('F', 426),
 ('x', 381),
 ('B', 348),
 ('O', 332),
 ('Y', 326),
 ('j', 319),
 ('C', 293),
 ('E', 287),
 ('z', 259),
 ('q', 217),
 ('L', 209),
 ('Q', 203),
 ('U', 193),
 ('V', 192),
 (';', 135),
 ('K', 79),
 (':', 69),
 ('J', 51),
 (')', 33),
 ('(', 30),
 ('“', 11),
 ('1', 11),
 ('3', 8),
 ('4', 6),
 ('Z', 5),
 ('0', 5),
 ('7', 4),
 ('9', 4),
 ('2', 3),
 ('X', 2),
 ('5', 2),
 ('*', 2),
 ('–', 1),
 ('~', 1),


In [7]:
set(text)

{'\n',
 ' ',
 '!',
 '"',
 "'",
 '(',
 ')',
 '*',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '\\',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '~',
 '–',
 '“'}

In [8]:
vocab = sorted(set(text))
vocab_to_int = {c : i for i,c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
embeddings = np.array([vocab_to_int[i] for i in text], dtype=np.int32)

vocab_to_int

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 "'": 4,
 '(': 5,
 ')': 6,
 '*': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '?': 23,
 'A': 24,
 'B': 25,
 'C': 26,
 'D': 27,
 'E': 28,
 'F': 29,
 'G': 30,
 'H': 31,
 'I': 32,
 'J': 33,
 'K': 34,
 'L': 35,
 'M': 36,
 'N': 37,
 'O': 38,
 'P': 39,
 'Q': 40,
 'R': 41,
 'S': 42,
 'T': 43,
 'U': 44,
 'V': 45,
 'W': 46,
 'X': 47,
 'Y': 48,
 'Z': 49,
 '\\': 50,
 'a': 51,
 'b': 52,
 'c': 53,
 'd': 54,
 'e': 55,
 'f': 56,
 'g': 57,
 'h': 58,
 'i': 59,
 'j': 60,
 'k': 61,
 'l': 62,
 'm': 63,
 'n': 64,
 'o': 65,
 'p': 66,
 'q': 67,
 'r': 68,
 's': 69,
 't': 70,
 'u': 71,
 'v': 72,
 'w': 73,
 'x': 74,
 'y': 75,
 'z': 76,
 '~': 77,
 '–': 78,
 '“': 79}

In [9]:
print ("Examples encodings (inputs to our NN) -->>")
print (text[:120])
print (embeddings[:120])

Examples encodings (inputs to our NN) -->>
Harry Potter and the Sorcerer's Stone 

CHAPTER ONE 

THE BOY WHO LIVED 

Mr. and Mrs. Dursley, of number four, Privet D
[31 51 68 68 75  1 39 65 70 70 55 68  1 51 64 54  1 70 58 55  1 42 65 68 53
 55 68 55 68  4 69  1 42 70 65 64 55  1  0  0 26 31 24 39 43 28 41  1 38 37
 28  1  0  0 43 31 28  1 25 38 48  1 46 31 38  1 35 32 45 28 27  1  0  0 36
 68 10  1 51 64 54  1 36 68 69 10  1 27 71 68 69 62 55 75  8  1 65 56  1 64
 71 63 52 55 68  1 56 65 71 68  8  1 39 68 59 72 55 70  1 27]


## RNN with LSTM Model Build and Optimization

In [10]:
def placeholders(batch_size, step_size):
    inputs = tf.placeholder(tf.int32, shape=(batch_size, step_size), name='inputs')
    targets = tf.placeholder(tf.int32, shape=(batch_size, step_size), name='targets')
    keep_prob = tf.placeholder(tf.float32, name= 'prob')
    
    return inputs, targets, keep_prob

In [11]:
def lstms(lstm_size, layers, batch_size, keep_prob):
    
    def build_cell(lstm_size, keep_prob):
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
    
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(layers)])
    state = cell.zero_state(batch_size, tf.float32)
    
    return cell, state

def rnn_output(lstm_output, input_size, output_size):
    sequence = tf.concat(lstm_output, axis=1)
    x = tf.reshape(sequence, [-1, input_size])
    
    with tf.variable_scope('softmax'):
        weights = tf.Variable(tf.truncated_normal(shape=(input_size, output_size), stddev=0.1))
        bias = tf.Variable(tf.zeros(output_size))
        
    logits = tf.matmul(x, weights) + bias
    predictions = tf.nn.softmax(logits, name='predictions')                          
    
    return predictions, logits

def losses(logits, y, lstm_size, num_classes):
    labels = tf.reshape(tf.one_hot(y, num_classes), logits.get_shape())
    loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
    
    return loss



In [12]:
batch_size = 128
num_steps = 100        
lstm_size = 512 
num_layers = 2         
learning_rate = 0.001  
prob = 0.5 
grad_clip = 5
num_classes = len(vocab)


def generate_batches(inputs, batch_size, num_steps):
    char_batch = batch_size * num_steps
    num_batches = len(inputs)//char_batch
    
    idx = char_batch * num_batches 
    inputs = inputs[:idx]
    inputs = inputs.reshape((batch_size, -1))
    
    for i in range(0, inputs.shape[1], num_steps):
        x = inputs[:, i : i+num_steps]
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        
        yield x, y
        
batches = generate_batches(embeddings, 10, 50)
x, y = next(batches)

print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[31 51 68 68 75  1 39 65 70 70]
 [ 1 69 66 65 61 55  1 51 52 65]
 [70 69  1 52 55 51 61 10  1  0]
 [64 65 69 55 10  1  0  0  3 48]
 [70 58 55 59 68  1 56 51 53 55]
 [56 65 75 69  1 69 64 55 55 68]
 [64 70  1 57 51 59 64 69  1 70]
 [ 1 51 64 65 70 58 55 68  1 68]
 [51 68 54  1 58 59 63  1 51 64]
 [65 62 65 57 75  8  1 31 55 68]]

y
 [[51 68 68 75  1 39 65 70 70 55]
 [69 66 65 61 55  1 51 52 65 71]
 [69  1 52 55 51 61 10  1  0  0]
 [65 69 55 10  1  0  0  3 48 55]
 [58 55 59 68  1 56 51 53 55 69]
 [65 75 69  1 69 64 55 55 68 59]
 [70  1 57 51 59 64 69  1 70 58]
 [51 64 65 70 58 55 68  1 68 55]
 [68 54  1 58 59 63  1 51 64 54]
 [62 65 57 75  8  1 31 55 68 63]]


Optimization

In [13]:
def cal_optimizer(loss, learning_rate, clipping):
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), clipping)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer


tf.reset_default_graph()

#input tensors
inputs, targets, keep_prob = placeholders(batch_size, num_steps)

#LSTM Cell
cell, initial_state = lstms(lstm_size, num_layers, batch_size, keep_prob)

## One hot encode inputs
one_hot_inputs = tf.one_hot(inputs, num_classes)

#Collect outputs
outputs, state = tf.nn.dynamic_rnn(cell, one_hot_inputs, initial_state = initial_state)
final_state = state

## Predictions and Logits
predictions, logits = rnn_output(outputs, lstm_size, num_classes)

#losses and optimizer(ADAM)
loss = losses(logits, targets, lstm_size, num_classes)
optimizer = cal_optimizer(loss, learning_rate, grad_clip)

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.



## Train Model

In [14]:
epochs = 100
save_every_n = 300

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    counter = 0
    for e in range(epochs):
        new_state = sess.run(initial_state)
        for x, y in generate_batches(embeddings, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed_dict = {inputs: x,
                    targets: y,
                    keep_prob: prob,
                    initial_state: new_state}
            batch_loss, new_state, _ = sess.run([loss, 
                                                 final_state, 
                                                 optimizer], 
                                                 feed_dict = feed_dict)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/100...  Training Step: 1...  Training loss: 4.3831...  7.9537 sec/batch
Epoch: 1/100...  Training Step: 2...  Training loss: 4.2996...  6.9390 sec/batch
Epoch: 1/100...  Training Step: 3...  Training loss: 3.9050...  7.0088 sec/batch
Epoch: 1/100...  Training Step: 4...  Training loss: 6.2413...  7.0486 sec/batch
Epoch: 1/100...  Training Step: 5...  Training loss: 4.1650...  6.9546 sec/batch
Epoch: 1/100...  Training Step: 6...  Training loss: 3.7128...  6.9698 sec/batch
Epoch: 1/100...  Training Step: 7...  Training loss: 3.6999...  6.7063 sec/batch
Epoch: 1/100...  Training Step: 8...  Training loss: 3.6570...  6.0619 sec/batch
Epoch: 1/100...  Training Step: 9...  Training loss: 3.5491...  5.7370 sec/batch
Epoch: 1/100...  Training Step: 10...  Training loss: 3.4639...  7.0736 sec/batch
Epoch: 1/100...  Training Step: 11...  Training loss: 3.4104...  5.9567 sec/batch
Epoch: 1/100...  Training Step: 12...  Training loss: 3.3785...  6.1217 sec/batch
Epoch: 1/100...  Training

Epoch: 3/100...  Training Step: 102...  Training loss: 3.0107...  5.8269 sec/batch
Epoch: 4/100...  Training Step: 103...  Training loss: 3.0601...  6.4722 sec/batch
Epoch: 4/100...  Training Step: 104...  Training loss: 2.9826...  6.4807 sec/batch
Epoch: 4/100...  Training Step: 105...  Training loss: 2.9702...  7.1150 sec/batch
Epoch: 4/100...  Training Step: 106...  Training loss: 2.9697...  7.0601 sec/batch
Epoch: 4/100...  Training Step: 107...  Training loss: 2.9659...  6.0087 sec/batch
Epoch: 4/100...  Training Step: 108...  Training loss: 2.9379...  6.4326 sec/batch
Epoch: 4/100...  Training Step: 109...  Training loss: 2.9261...  6.1798 sec/batch
Epoch: 4/100...  Training Step: 110...  Training loss: 2.9298...  6.2015 sec/batch
Epoch: 4/100...  Training Step: 111...  Training loss: 2.8956...  7.8192 sec/batch
Epoch: 4/100...  Training Step: 112...  Training loss: 2.9273...  7.7787 sec/batch
Epoch: 4/100...  Training Step: 113...  Training loss: 2.9211...  7.4715 sec/batch
Epoc

Epoch: 6/100...  Training Step: 201...  Training loss: 2.3872...  5.8535 sec/batch
Epoch: 6/100...  Training Step: 202...  Training loss: 2.3899...  5.8595 sec/batch
Epoch: 6/100...  Training Step: 203...  Training loss: 2.3905...  5.8453 sec/batch
Epoch: 6/100...  Training Step: 204...  Training loss: 2.3719...  5.8504 sec/batch
Epoch: 7/100...  Training Step: 205...  Training loss: 2.4583...  5.9682 sec/batch
Epoch: 7/100...  Training Step: 206...  Training loss: 2.3683...  5.8257 sec/batch
Epoch: 7/100...  Training Step: 207...  Training loss: 2.3587...  5.8360 sec/batch
Epoch: 7/100...  Training Step: 208...  Training loss: 2.3789...  6.4006 sec/batch
Epoch: 7/100...  Training Step: 209...  Training loss: 2.3792...  6.3540 sec/batch
Epoch: 7/100...  Training Step: 210...  Training loss: 2.3429...  6.1193 sec/batch
Epoch: 7/100...  Training Step: 211...  Training loss: 2.3531...  6.0875 sec/batch
Epoch: 7/100...  Training Step: 212...  Training loss: 2.3388...  5.9820 sec/batch
Epoc

Epoch: 9/100...  Training Step: 300...  Training loss: 2.1235...  5.7873 sec/batch
Epoch: 9/100...  Training Step: 301...  Training loss: 2.1482...  5.7787 sec/batch
Epoch: 9/100...  Training Step: 302...  Training loss: 2.1586...  5.8909 sec/batch
Epoch: 9/100...  Training Step: 303...  Training loss: 2.1430...  5.8013 sec/batch
Epoch: 9/100...  Training Step: 304...  Training loss: 2.1449...  5.9000 sec/batch
Epoch: 9/100...  Training Step: 305...  Training loss: 2.1679...  5.8065 sec/batch
Epoch: 9/100...  Training Step: 306...  Training loss: 2.1159...  5.8419 sec/batch
Epoch: 10/100...  Training Step: 307...  Training loss: 2.2105...  5.8311 sec/batch
Epoch: 10/100...  Training Step: 308...  Training loss: 2.1252...  5.8003 sec/batch
Epoch: 10/100...  Training Step: 309...  Training loss: 2.1164...  5.8841 sec/batch
Epoch: 10/100...  Training Step: 310...  Training loss: 2.1515...  5.9094 sec/batch
Epoch: 10/100...  Training Step: 311...  Training loss: 2.1425...  5.9278 sec/batch

Epoch: 12/100...  Training Step: 398...  Training loss: 1.9838...  5.8529 sec/batch
Epoch: 12/100...  Training Step: 399...  Training loss: 1.9425...  5.8795 sec/batch
Epoch: 12/100...  Training Step: 400...  Training loss: 1.9670...  5.7866 sec/batch
Epoch: 12/100...  Training Step: 401...  Training loss: 1.9698...  5.8377 sec/batch
Epoch: 12/100...  Training Step: 402...  Training loss: 1.9558...  5.8156 sec/batch
Epoch: 12/100...  Training Step: 403...  Training loss: 1.9911...  5.8106 sec/batch
Epoch: 12/100...  Training Step: 404...  Training loss: 2.0027...  5.8643 sec/batch
Epoch: 12/100...  Training Step: 405...  Training loss: 1.9864...  5.7963 sec/batch
Epoch: 12/100...  Training Step: 406...  Training loss: 1.9840...  5.8870 sec/batch
Epoch: 12/100...  Training Step: 407...  Training loss: 2.0046...  5.9130 sec/batch
Epoch: 12/100...  Training Step: 408...  Training loss: 1.9479...  5.8456 sec/batch
Epoch: 13/100...  Training Step: 409...  Training loss: 2.0627...  5.8566 se

Epoch: 15/100...  Training Step: 496...  Training loss: 1.8513...  6.0960 sec/batch
Epoch: 15/100...  Training Step: 497...  Training loss: 1.8639...  6.0457 sec/batch
Epoch: 15/100...  Training Step: 498...  Training loss: 1.8209...  5.8065 sec/batch
Epoch: 15/100...  Training Step: 499...  Training loss: 1.8432...  5.8304 sec/batch
Epoch: 15/100...  Training Step: 500...  Training loss: 1.8628...  5.7965 sec/batch
Epoch: 15/100...  Training Step: 501...  Training loss: 1.8163...  5.8155 sec/batch
Epoch: 15/100...  Training Step: 502...  Training loss: 1.8386...  5.7973 sec/batch
Epoch: 15/100...  Training Step: 503...  Training loss: 1.8298...  5.8184 sec/batch
Epoch: 15/100...  Training Step: 504...  Training loss: 1.8348...  5.8103 sec/batch
Epoch: 15/100...  Training Step: 505...  Training loss: 1.8587...  5.8285 sec/batch
Epoch: 15/100...  Training Step: 506...  Training loss: 1.8814...  5.8387 sec/batch
Epoch: 15/100...  Training Step: 507...  Training loss: 1.8612...  5.8662 se

Epoch: 18/100...  Training Step: 594...  Training loss: 1.7840...  5.7867 sec/batch
Epoch: 18/100...  Training Step: 595...  Training loss: 1.7817...  5.8098 sec/batch
Epoch: 18/100...  Training Step: 596...  Training loss: 1.7489...  5.9711 sec/batch
Epoch: 18/100...  Training Step: 597...  Training loss: 1.7658...  5.8208 sec/batch
Epoch: 18/100...  Training Step: 598...  Training loss: 1.7368...  5.9004 sec/batch
Epoch: 18/100...  Training Step: 599...  Training loss: 1.7653...  5.8372 sec/batch
Epoch: 18/100...  Training Step: 600...  Training loss: 1.7249...  5.8483 sec/batch
Epoch: 18/100...  Training Step: 601...  Training loss: 1.7390...  5.8175 sec/batch
Epoch: 18/100...  Training Step: 602...  Training loss: 1.7531...  5.8702 sec/batch
Epoch: 18/100...  Training Step: 603...  Training loss: 1.7215...  5.8765 sec/batch
Epoch: 18/100...  Training Step: 604...  Training loss: 1.7285...  5.8388 sec/batch
Epoch: 18/100...  Training Step: 605...  Training loss: 1.7327...  5.8165 se

Epoch: 21/100...  Training Step: 692...  Training loss: 1.7122...  5.8064 sec/batch
Epoch: 21/100...  Training Step: 693...  Training loss: 1.6962...  5.8552 sec/batch
Epoch: 21/100...  Training Step: 694...  Training loss: 1.6821...  5.8404 sec/batch
Epoch: 21/100...  Training Step: 695...  Training loss: 1.6622...  5.8523 sec/batch
Epoch: 21/100...  Training Step: 696...  Training loss: 1.6978...  5.8540 sec/batch
Epoch: 21/100...  Training Step: 697...  Training loss: 1.7094...  5.8331 sec/batch
Epoch: 21/100...  Training Step: 698...  Training loss: 1.6713...  5.8599 sec/batch
Epoch: 21/100...  Training Step: 699...  Training loss: 1.6846...  5.8433 sec/batch
Epoch: 21/100...  Training Step: 700...  Training loss: 1.6513...  5.8369 sec/batch
Epoch: 21/100...  Training Step: 701...  Training loss: 1.6730...  5.9123 sec/batch
Epoch: 21/100...  Training Step: 702...  Training loss: 1.6355...  5.8472 sec/batch
Epoch: 21/100...  Training Step: 703...  Training loss: 1.6606...  5.7761 se

Epoch: 24/100...  Training Step: 790...  Training loss: 1.6037...  5.8062 sec/batch
Epoch: 24/100...  Training Step: 791...  Training loss: 1.5841...  5.8187 sec/batch
Epoch: 24/100...  Training Step: 792...  Training loss: 1.6268...  5.8844 sec/batch
Epoch: 24/100...  Training Step: 793...  Training loss: 1.6178...  5.7953 sec/batch
Epoch: 24/100...  Training Step: 794...  Training loss: 1.6282...  6.5557 sec/batch
Epoch: 24/100...  Training Step: 795...  Training loss: 1.6334...  5.8660 sec/batch
Epoch: 24/100...  Training Step: 796...  Training loss: 1.6070...  5.9670 sec/batch
Epoch: 24/100...  Training Step: 797...  Training loss: 1.5928...  5.8259 sec/batch
Epoch: 24/100...  Training Step: 798...  Training loss: 1.6314...  5.8348 sec/batch
Epoch: 24/100...  Training Step: 799...  Training loss: 1.6359...  5.8119 sec/batch
Epoch: 24/100...  Training Step: 800...  Training loss: 1.6012...  5.9014 sec/batch
Epoch: 24/100...  Training Step: 801...  Training loss: 1.6078...  5.7897 se

Epoch: 27/100...  Training Step: 888...  Training loss: 1.5862...  5.8303 sec/batch
Epoch: 27/100...  Training Step: 889...  Training loss: 1.5778...  5.7545 sec/batch
Epoch: 27/100...  Training Step: 890...  Training loss: 1.5506...  5.8521 sec/batch
Epoch: 27/100...  Training Step: 891...  Training loss: 1.5613...  5.8056 sec/batch
Epoch: 27/100...  Training Step: 892...  Training loss: 1.5367...  5.7736 sec/batch
Epoch: 27/100...  Training Step: 893...  Training loss: 1.5345...  5.8594 sec/batch
Epoch: 27/100...  Training Step: 894...  Training loss: 1.5584...  5.7972 sec/batch
Epoch: 27/100...  Training Step: 895...  Training loss: 1.5623...  5.8343 sec/batch
Epoch: 27/100...  Training Step: 896...  Training loss: 1.5669...  5.7843 sec/batch
Epoch: 27/100...  Training Step: 897...  Training loss: 1.5736...  5.8837 sec/batch
Epoch: 27/100...  Training Step: 898...  Training loss: 1.5523...  5.8847 sec/batch
Epoch: 27/100...  Training Step: 899...  Training loss: 1.5310...  5.8321 se

Epoch: 29/100...  Training Step: 986...  Training loss: 1.5090...  5.8499 sec/batch
Epoch: 30/100...  Training Step: 987...  Training loss: 1.5773...  5.8418 sec/batch
Epoch: 30/100...  Training Step: 988...  Training loss: 1.4989...  5.9464 sec/batch
Epoch: 30/100...  Training Step: 989...  Training loss: 1.5055...  5.8530 sec/batch
Epoch: 30/100...  Training Step: 990...  Training loss: 1.5333...  5.9141 sec/batch
Epoch: 30/100...  Training Step: 991...  Training loss: 1.5211...  5.8160 sec/batch
Epoch: 30/100...  Training Step: 992...  Training loss: 1.4912...  5.8552 sec/batch
Epoch: 30/100...  Training Step: 993...  Training loss: 1.5129...  5.8255 sec/batch
Epoch: 30/100...  Training Step: 994...  Training loss: 1.4885...  5.8116 sec/batch
Epoch: 30/100...  Training Step: 995...  Training loss: 1.4743...  5.8475 sec/batch
Epoch: 30/100...  Training Step: 996...  Training loss: 1.5127...  5.7713 sec/batch
Epoch: 30/100...  Training Step: 997...  Training loss: 1.5141...  5.9133 se

Epoch: 32/100...  Training Step: 1083...  Training loss: 1.4844...  5.8760 sec/batch
Epoch: 32/100...  Training Step: 1084...  Training loss: 1.4790...  5.8090 sec/batch
Epoch: 32/100...  Training Step: 1085...  Training loss: 1.4609...  5.8028 sec/batch
Epoch: 32/100...  Training Step: 1086...  Training loss: 1.4996...  5.8059 sec/batch
Epoch: 32/100...  Training Step: 1087...  Training loss: 1.4997...  5.8507 sec/batch
Epoch: 32/100...  Training Step: 1088...  Training loss: 1.4645...  5.8323 sec/batch
Epoch: 33/100...  Training Step: 1089...  Training loss: 1.5300...  5.8271 sec/batch
Epoch: 33/100...  Training Step: 1090...  Training loss: 1.4499...  6.1039 sec/batch
Epoch: 33/100...  Training Step: 1091...  Training loss: 1.4566...  5.8573 sec/batch
Epoch: 33/100...  Training Step: 1092...  Training loss: 1.4948...  5.7839 sec/batch
Epoch: 33/100...  Training Step: 1093...  Training loss: 1.4750...  5.8214 sec/batch
Epoch: 33/100...  Training Step: 1094...  Training loss: 1.4364..

Epoch: 35/100...  Training Step: 1180...  Training loss: 1.4101...  7.3233 sec/batch
Epoch: 35/100...  Training Step: 1181...  Training loss: 1.3954...  5.8903 sec/batch
Epoch: 35/100...  Training Step: 1182...  Training loss: 1.4073...  7.3741 sec/batch
Epoch: 35/100...  Training Step: 1183...  Training loss: 1.3967...  5.9178 sec/batch
Epoch: 35/100...  Training Step: 1184...  Training loss: 1.4053...  5.8292 sec/batch
Epoch: 35/100...  Training Step: 1185...  Training loss: 1.4387...  6.0199 sec/batch
Epoch: 35/100...  Training Step: 1186...  Training loss: 1.4402...  6.1969 sec/batch
Epoch: 35/100...  Training Step: 1187...  Training loss: 1.4184...  6.0462 sec/batch
Epoch: 35/100...  Training Step: 1188...  Training loss: 1.4471...  5.7721 sec/batch
Epoch: 35/100...  Training Step: 1189...  Training loss: 1.4564...  5.8243 sec/batch
Epoch: 35/100...  Training Step: 1190...  Training loss: 1.4135...  5.7939 sec/batch
Epoch: 36/100...  Training Step: 1191...  Training loss: 1.4812..

Epoch: 38/100...  Training Step: 1277...  Training loss: 1.3929...  5.8174 sec/batch
Epoch: 38/100...  Training Step: 1278...  Training loss: 1.3717...  5.7785 sec/batch
Epoch: 38/100...  Training Step: 1279...  Training loss: 1.3878...  5.8559 sec/batch
Epoch: 38/100...  Training Step: 1280...  Training loss: 1.3587...  5.7721 sec/batch
Epoch: 38/100...  Training Step: 1281...  Training loss: 1.3786...  5.8212 sec/batch
Epoch: 38/100...  Training Step: 1282...  Training loss: 1.3726...  5.8677 sec/batch
Epoch: 38/100...  Training Step: 1283...  Training loss: 1.3658...  5.8383 sec/batch
Epoch: 38/100...  Training Step: 1284...  Training loss: 1.3689...  5.7712 sec/batch
Epoch: 38/100...  Training Step: 1285...  Training loss: 1.3502...  5.8430 sec/batch
Epoch: 38/100...  Training Step: 1286...  Training loss: 1.3659...  5.8746 sec/batch
Epoch: 38/100...  Training Step: 1287...  Training loss: 1.3928...  5.8128 sec/batch
Epoch: 38/100...  Training Step: 1288...  Training loss: 1.3980..

Epoch: 41/100...  Training Step: 1374...  Training loss: 1.3672...  5.7690 sec/batch
Epoch: 41/100...  Training Step: 1375...  Training loss: 1.3415...  5.8489 sec/batch
Epoch: 41/100...  Training Step: 1376...  Training loss: 1.3776...  5.8662 sec/batch
Epoch: 41/100...  Training Step: 1377...  Training loss: 1.3945...  5.7737 sec/batch
Epoch: 41/100...  Training Step: 1378...  Training loss: 1.3599...  5.8603 sec/batch
Epoch: 41/100...  Training Step: 1379...  Training loss: 1.3666...  5.8416 sec/batch
Epoch: 41/100...  Training Step: 1380...  Training loss: 1.3371...  5.8456 sec/batch
Epoch: 41/100...  Training Step: 1381...  Training loss: 1.3597...  5.8260 sec/batch
Epoch: 41/100...  Training Step: 1382...  Training loss: 1.3261...  5.8185 sec/batch
Epoch: 41/100...  Training Step: 1383...  Training loss: 1.3496...  5.7900 sec/batch
Epoch: 41/100...  Training Step: 1384...  Training loss: 1.3370...  5.7897 sec/batch
Epoch: 41/100...  Training Step: 1385...  Training loss: 1.3299..

Epoch: 44/100...  Training Step: 1471...  Training loss: 1.2923...  5.8440 sec/batch
Epoch: 44/100...  Training Step: 1472...  Training loss: 1.3342...  5.8115 sec/batch
Epoch: 44/100...  Training Step: 1473...  Training loss: 1.3386...  5.9293 sec/batch
Epoch: 44/100...  Training Step: 1474...  Training loss: 1.3386...  5.8896 sec/batch
Epoch: 44/100...  Training Step: 1475...  Training loss: 1.3472...  5.7830 sec/batch
Epoch: 44/100...  Training Step: 1476...  Training loss: 1.3358...  5.7875 sec/batch
Epoch: 44/100...  Training Step: 1477...  Training loss: 1.3124...  5.8118 sec/batch
Epoch: 44/100...  Training Step: 1478...  Training loss: 1.3399...  5.8099 sec/batch
Epoch: 44/100...  Training Step: 1479...  Training loss: 1.3479...  5.8172 sec/batch
Epoch: 44/100...  Training Step: 1480...  Training loss: 1.3242...  5.8230 sec/batch
Epoch: 44/100...  Training Step: 1481...  Training loss: 1.3240...  5.8781 sec/batch
Epoch: 44/100...  Training Step: 1482...  Training loss: 1.3066..

Epoch: 47/100...  Training Step: 1568...  Training loss: 1.3290...  5.7754 sec/batch
Epoch: 47/100...  Training Step: 1569...  Training loss: 1.3239...  5.8107 sec/batch
Epoch: 47/100...  Training Step: 1570...  Training loss: 1.2868...  5.8346 sec/batch
Epoch: 47/100...  Training Step: 1571...  Training loss: 1.3041...  5.8533 sec/batch
Epoch: 47/100...  Training Step: 1572...  Training loss: 1.2803...  5.7348 sec/batch
Epoch: 47/100...  Training Step: 1573...  Training loss: 1.2680...  5.8543 sec/batch
Epoch: 47/100...  Training Step: 1574...  Training loss: 1.3035...  5.8303 sec/batch
Epoch: 47/100...  Training Step: 1575...  Training loss: 1.3066...  5.8337 sec/batch
Epoch: 47/100...  Training Step: 1576...  Training loss: 1.3030...  5.8331 sec/batch
Epoch: 47/100...  Training Step: 1577...  Training loss: 1.3089...  5.8041 sec/batch
Epoch: 47/100...  Training Step: 1578...  Training loss: 1.3087...  5.8298 sec/batch
Epoch: 47/100...  Training Step: 1579...  Training loss: 1.2853..

Epoch: 49/100...  Training Step: 1665...  Training loss: 1.2969...  5.8239 sec/batch
Epoch: 49/100...  Training Step: 1666...  Training loss: 1.2631...  5.7696 sec/batch
Epoch: 50/100...  Training Step: 1667...  Training loss: 1.3315...  5.8671 sec/batch
Epoch: 50/100...  Training Step: 1668...  Training loss: 1.2628...  5.7625 sec/batch
Epoch: 50/100...  Training Step: 1669...  Training loss: 1.2689...  5.8215 sec/batch
Epoch: 50/100...  Training Step: 1670...  Training loss: 1.2970...  5.7894 sec/batch
Epoch: 50/100...  Training Step: 1671...  Training loss: 1.2918...  5.8157 sec/batch
Epoch: 50/100...  Training Step: 1672...  Training loss: 1.2617...  5.8520 sec/batch
Epoch: 50/100...  Training Step: 1673...  Training loss: 1.2771...  6.3243 sec/batch
Epoch: 50/100...  Training Step: 1674...  Training loss: 1.2454...  5.9936 sec/batch
Epoch: 50/100...  Training Step: 1675...  Training loss: 1.2443...  5.9962 sec/batch
Epoch: 50/100...  Training Step: 1676...  Training loss: 1.2714..

Epoch: 52/100...  Training Step: 1762...  Training loss: 1.2326...  5.8440 sec/batch
Epoch: 52/100...  Training Step: 1763...  Training loss: 1.2608...  5.8437 sec/batch
Epoch: 52/100...  Training Step: 1764...  Training loss: 1.2576...  5.8121 sec/batch
Epoch: 52/100...  Training Step: 1765...  Training loss: 1.2304...  5.8043 sec/batch
Epoch: 52/100...  Training Step: 1766...  Training loss: 1.2600...  5.8484 sec/batch
Epoch: 52/100...  Training Step: 1767...  Training loss: 1.2723...  5.8191 sec/batch
Epoch: 52/100...  Training Step: 1768...  Training loss: 1.2349...  5.8124 sec/batch
Epoch: 53/100...  Training Step: 1769...  Training loss: 1.3036...  5.8493 sec/batch
Epoch: 53/100...  Training Step: 1770...  Training loss: 1.2350...  5.7804 sec/batch
Epoch: 53/100...  Training Step: 1771...  Training loss: 1.2379...  5.7910 sec/batch
Epoch: 53/100...  Training Step: 1772...  Training loss: 1.2750...  5.8338 sec/batch
Epoch: 53/100...  Training Step: 1773...  Training loss: 1.2534..

Epoch: 55/100...  Training Step: 1859...  Training loss: 1.2227...  6.1995 sec/batch
Epoch: 55/100...  Training Step: 1860...  Training loss: 1.2081...  5.8574 sec/batch
Epoch: 55/100...  Training Step: 1861...  Training loss: 1.1973...  5.8139 sec/batch
Epoch: 55/100...  Training Step: 1862...  Training loss: 1.2184...  5.8886 sec/batch
Epoch: 55/100...  Training Step: 1863...  Training loss: 1.2028...  5.8468 sec/batch
Epoch: 55/100...  Training Step: 1864...  Training loss: 1.2138...  5.7894 sec/batch
Epoch: 55/100...  Training Step: 1865...  Training loss: 1.2292...  5.8593 sec/batch
Epoch: 55/100...  Training Step: 1866...  Training loss: 1.2258...  5.8888 sec/batch
Epoch: 55/100...  Training Step: 1867...  Training loss: 1.1955...  5.7845 sec/batch
Epoch: 55/100...  Training Step: 1868...  Training loss: 1.2336...  5.7840 sec/batch
Epoch: 55/100...  Training Step: 1869...  Training loss: 1.2360...  5.7933 sec/batch
Epoch: 55/100...  Training Step: 1870...  Training loss: 1.2063..

Epoch: 58/100...  Training Step: 1956...  Training loss: 1.1982...  5.7820 sec/batch
Epoch: 58/100...  Training Step: 1957...  Training loss: 1.1835...  5.8833 sec/batch
Epoch: 58/100...  Training Step: 1958...  Training loss: 1.1752...  5.7889 sec/batch
Epoch: 58/100...  Training Step: 1959...  Training loss: 1.2025...  5.8979 sec/batch
Epoch: 58/100...  Training Step: 1960...  Training loss: 1.1668...  5.8316 sec/batch
Epoch: 58/100...  Training Step: 1961...  Training loss: 1.2002...  5.8092 sec/batch
Epoch: 58/100...  Training Step: 1962...  Training loss: 1.1769...  6.0486 sec/batch
Epoch: 58/100...  Training Step: 1963...  Training loss: 1.1809...  5.7879 sec/batch
Epoch: 58/100...  Training Step: 1964...  Training loss: 1.1850...  5.7751 sec/batch
Epoch: 58/100...  Training Step: 1965...  Training loss: 1.1716...  5.9844 sec/batch
Epoch: 58/100...  Training Step: 1966...  Training loss: 1.1705...  5.8208 sec/batch
Epoch: 58/100...  Training Step: 1967...  Training loss: 1.1950..

Epoch: 61/100...  Training Step: 2053...  Training loss: 1.1737...  5.8076 sec/batch
Epoch: 61/100...  Training Step: 2054...  Training loss: 1.1806...  5.7823 sec/batch
Epoch: 61/100...  Training Step: 2055...  Training loss: 1.1490...  5.8202 sec/batch
Epoch: 61/100...  Training Step: 2056...  Training loss: 1.1746...  5.7767 sec/batch
Epoch: 61/100...  Training Step: 2057...  Training loss: 1.1774...  5.8450 sec/batch
Epoch: 61/100...  Training Step: 2058...  Training loss: 1.1730...  5.8823 sec/batch
Epoch: 61/100...  Training Step: 2059...  Training loss: 1.1687...  5.8125 sec/batch
Epoch: 61/100...  Training Step: 2060...  Training loss: 1.1488...  5.8319 sec/batch
Epoch: 61/100...  Training Step: 2061...  Training loss: 1.1550...  5.8193 sec/batch
Epoch: 61/100...  Training Step: 2062...  Training loss: 1.1416...  5.8313 sec/batch
Epoch: 61/100...  Training Step: 2063...  Training loss: 1.1623...  5.8096 sec/batch
Epoch: 61/100...  Training Step: 2064...  Training loss: 1.1547..

Epoch: 64/100...  Training Step: 2150...  Training loss: 1.1311...  5.9120 sec/batch
Epoch: 64/100...  Training Step: 2151...  Training loss: 1.1165...  5.7953 sec/batch
Epoch: 64/100...  Training Step: 2152...  Training loss: 1.1446...  5.8398 sec/batch
Epoch: 64/100...  Training Step: 2153...  Training loss: 1.1456...  5.8283 sec/batch
Epoch: 64/100...  Training Step: 2154...  Training loss: 1.1491...  5.8449 sec/batch
Epoch: 64/100...  Training Step: 2155...  Training loss: 1.1534...  5.8608 sec/batch
Epoch: 64/100...  Training Step: 2156...  Training loss: 1.1616...  5.8386 sec/batch
Epoch: 64/100...  Training Step: 2157...  Training loss: 1.1289...  5.8116 sec/batch
Epoch: 64/100...  Training Step: 2158...  Training loss: 1.1593...  5.8197 sec/batch
Epoch: 64/100...  Training Step: 2159...  Training loss: 1.1556...  5.9076 sec/batch
Epoch: 64/100...  Training Step: 2160...  Training loss: 1.1360...  5.8014 sec/batch
Epoch: 64/100...  Training Step: 2161...  Training loss: 1.1358..

Epoch: 67/100...  Training Step: 2247...  Training loss: 1.1157...  5.8724 sec/batch
Epoch: 67/100...  Training Step: 2248...  Training loss: 1.1497...  5.7764 sec/batch
Epoch: 67/100...  Training Step: 2249...  Training loss: 1.1420...  5.7591 sec/batch
Epoch: 67/100...  Training Step: 2250...  Training loss: 1.1075...  5.8560 sec/batch
Epoch: 67/100...  Training Step: 2251...  Training loss: 1.1305...  5.8501 sec/batch
Epoch: 67/100...  Training Step: 2252...  Training loss: 1.1106...  5.7706 sec/batch
Epoch: 67/100...  Training Step: 2253...  Training loss: 1.0976...  5.9550 sec/batch
Epoch: 67/100...  Training Step: 2254...  Training loss: 1.1389...  5.7982 sec/batch
Epoch: 67/100...  Training Step: 2255...  Training loss: 1.1291...  5.7580 sec/batch
Epoch: 67/100...  Training Step: 2256...  Training loss: 1.1467...  5.8159 sec/batch
Epoch: 67/100...  Training Step: 2257...  Training loss: 1.1280...  5.8111 sec/batch
Epoch: 67/100...  Training Step: 2258...  Training loss: 1.1347..

Epoch: 69/100...  Training Step: 2344...  Training loss: 1.1189...  5.8235 sec/batch
Epoch: 69/100...  Training Step: 2345...  Training loss: 1.1142...  5.8677 sec/batch
Epoch: 69/100...  Training Step: 2346...  Training loss: 1.0902...  5.8354 sec/batch
Epoch: 70/100...  Training Step: 2347...  Training loss: 1.1634...  5.8287 sec/batch
Epoch: 70/100...  Training Step: 2348...  Training loss: 1.0977...  5.7696 sec/batch
Epoch: 70/100...  Training Step: 2349...  Training loss: 1.1102...  5.8158 sec/batch
Epoch: 70/100...  Training Step: 2350...  Training loss: 1.1220...  5.7799 sec/batch
Epoch: 70/100...  Training Step: 2351...  Training loss: 1.1151...  5.7603 sec/batch
Epoch: 70/100...  Training Step: 2352...  Training loss: 1.0857...  5.7989 sec/batch
Epoch: 70/100...  Training Step: 2353...  Training loss: 1.1032...  5.8528 sec/batch
Epoch: 70/100...  Training Step: 2354...  Training loss: 1.0863...  5.8205 sec/batch
Epoch: 70/100...  Training Step: 2355...  Training loss: 1.0801..

Epoch: 72/100...  Training Step: 2441...  Training loss: 1.0669...  5.8178 sec/batch
Epoch: 72/100...  Training Step: 2442...  Training loss: 1.0706...  5.7856 sec/batch
Epoch: 72/100...  Training Step: 2443...  Training loss: 1.0917...  5.8366 sec/batch
Epoch: 72/100...  Training Step: 2444...  Training loss: 1.0899...  5.8190 sec/batch
Epoch: 72/100...  Training Step: 2445...  Training loss: 1.0745...  5.8356 sec/batch
Epoch: 72/100...  Training Step: 2446...  Training loss: 1.0890...  5.7450 sec/batch
Epoch: 72/100...  Training Step: 2447...  Training loss: 1.0911...  5.8143 sec/batch
Epoch: 72/100...  Training Step: 2448...  Training loss: 1.0724...  5.9371 sec/batch
Epoch: 73/100...  Training Step: 2449...  Training loss: 1.1425...  5.8501 sec/batch
Epoch: 73/100...  Training Step: 2450...  Training loss: 1.0717...  5.8166 sec/batch
Epoch: 73/100...  Training Step: 2451...  Training loss: 1.0727...  5.8720 sec/batch
Epoch: 73/100...  Training Step: 2452...  Training loss: 1.0952..

Epoch: 75/100...  Training Step: 2538...  Training loss: 1.0530...  5.8411 sec/batch
Epoch: 75/100...  Training Step: 2539...  Training loss: 1.0675...  5.8251 sec/batch
Epoch: 75/100...  Training Step: 2540...  Training loss: 1.0422...  5.8619 sec/batch
Epoch: 75/100...  Training Step: 2541...  Training loss: 1.0527...  5.8336 sec/batch
Epoch: 75/100...  Training Step: 2542...  Training loss: 1.0681...  5.7815 sec/batch
Epoch: 75/100...  Training Step: 2543...  Training loss: 1.0414...  5.8672 sec/batch
Epoch: 75/100...  Training Step: 2544...  Training loss: 1.0527...  5.8441 sec/batch
Epoch: 75/100...  Training Step: 2545...  Training loss: 1.0609...  5.7782 sec/batch
Epoch: 75/100...  Training Step: 2546...  Training loss: 1.0661...  5.8259 sec/batch
Epoch: 75/100...  Training Step: 2547...  Training loss: 1.0472...  5.8143 sec/batch
Epoch: 75/100...  Training Step: 2548...  Training loss: 1.0822...  5.7694 sec/batch
Epoch: 75/100...  Training Step: 2549...  Training loss: 1.0853..

Epoch: 78/100...  Training Step: 2635...  Training loss: 1.0453...  5.8386 sec/batch
Epoch: 78/100...  Training Step: 2636...  Training loss: 1.0417...  5.8439 sec/batch
Epoch: 78/100...  Training Step: 2637...  Training loss: 1.0364...  5.7815 sec/batch
Epoch: 78/100...  Training Step: 2638...  Training loss: 1.0165...  5.7756 sec/batch
Epoch: 78/100...  Training Step: 2639...  Training loss: 1.0355...  5.8951 sec/batch
Epoch: 78/100...  Training Step: 2640...  Training loss: 1.0211...  5.8170 sec/batch
Epoch: 78/100...  Training Step: 2641...  Training loss: 1.0541...  5.8481 sec/batch
Epoch: 78/100...  Training Step: 2642...  Training loss: 1.0275...  5.9190 sec/batch
Epoch: 78/100...  Training Step: 2643...  Training loss: 1.0306...  5.8907 sec/batch
Epoch: 78/100...  Training Step: 2644...  Training loss: 1.0366...  5.8553 sec/batch
Epoch: 78/100...  Training Step: 2645...  Training loss: 1.0241...  5.8075 sec/batch
Epoch: 78/100...  Training Step: 2646...  Training loss: 1.0320..

Epoch: 81/100...  Training Step: 2732...  Training loss: 1.0077...  6.3159 sec/batch
Epoch: 81/100...  Training Step: 2733...  Training loss: 1.0320...  6.2823 sec/batch
Epoch: 81/100...  Training Step: 2734...  Training loss: 1.0355...  5.9673 sec/batch
Epoch: 81/100...  Training Step: 2735...  Training loss: 1.0135...  6.1067 sec/batch
Epoch: 81/100...  Training Step: 2736...  Training loss: 1.0441...  6.6636 sec/batch
Epoch: 81/100...  Training Step: 2737...  Training loss: 1.0261...  6.6337 sec/batch
Epoch: 81/100...  Training Step: 2738...  Training loss: 1.0185...  5.9333 sec/batch
Epoch: 81/100...  Training Step: 2739...  Training loss: 1.0334...  5.8696 sec/batch
Epoch: 81/100...  Training Step: 2740...  Training loss: 1.0033...  6.3433 sec/batch
Epoch: 81/100...  Training Step: 2741...  Training loss: 1.0283...  5.9760 sec/batch
Epoch: 81/100...  Training Step: 2742...  Training loss: 1.0000...  6.6921 sec/batch
Epoch: 81/100...  Training Step: 2743...  Training loss: 1.0315..

Epoch: 84/100...  Training Step: 2829...  Training loss: 0.9950...  5.8337 sec/batch
Epoch: 84/100...  Training Step: 2830...  Training loss: 0.9932...  6.5940 sec/batch
Epoch: 84/100...  Training Step: 2831...  Training loss: 0.9778...  5.8577 sec/batch
Epoch: 84/100...  Training Step: 2832...  Training loss: 1.0077...  5.8584 sec/batch
Epoch: 84/100...  Training Step: 2833...  Training loss: 1.0032...  5.8134 sec/batch
Epoch: 84/100...  Training Step: 2834...  Training loss: 1.0105...  5.8157 sec/batch
Epoch: 84/100...  Training Step: 2835...  Training loss: 1.0064...  5.8819 sec/batch
Epoch: 84/100...  Training Step: 2836...  Training loss: 1.0073...  5.7554 sec/batch
Epoch: 84/100...  Training Step: 2837...  Training loss: 0.9974...  5.8016 sec/batch
Epoch: 84/100...  Training Step: 2838...  Training loss: 1.0118...  5.7748 sec/batch
Epoch: 84/100...  Training Step: 2839...  Training loss: 1.0223...  5.8539 sec/batch
Epoch: 84/100...  Training Step: 2840...  Training loss: 0.9934..

Epoch: 87/100...  Training Step: 2926...  Training loss: 0.9714...  5.8414 sec/batch
Epoch: 87/100...  Training Step: 2927...  Training loss: 0.9751...  5.8314 sec/batch
Epoch: 87/100...  Training Step: 2928...  Training loss: 0.9972...  5.8022 sec/batch
Epoch: 87/100...  Training Step: 2929...  Training loss: 0.9880...  5.7696 sec/batch
Epoch: 87/100...  Training Step: 2930...  Training loss: 0.9626...  6.2103 sec/batch
Epoch: 87/100...  Training Step: 2931...  Training loss: 0.9735...  6.4030 sec/batch
Epoch: 87/100...  Training Step: 2932...  Training loss: 0.9745...  6.0715 sec/batch
Epoch: 87/100...  Training Step: 2933...  Training loss: 0.9561...  5.8721 sec/batch
Epoch: 87/100...  Training Step: 2934...  Training loss: 0.9771...  5.8284 sec/batch
Epoch: 87/100...  Training Step: 2935...  Training loss: 0.9774...  5.8426 sec/batch
Epoch: 87/100...  Training Step: 2936...  Training loss: 0.9835...  5.9896 sec/batch
Epoch: 87/100...  Training Step: 2937...  Training loss: 0.9880..

Epoch: 89/100...  Training Step: 3023...  Training loss: 0.9540...  5.8481 sec/batch
Epoch: 89/100...  Training Step: 3024...  Training loss: 0.9707...  5.7538 sec/batch
Epoch: 89/100...  Training Step: 3025...  Training loss: 0.9738...  5.8336 sec/batch
Epoch: 89/100...  Training Step: 3026...  Training loss: 0.9599...  5.8644 sec/batch
Epoch: 90/100...  Training Step: 3027...  Training loss: 1.0089...  6.7352 sec/batch
Epoch: 90/100...  Training Step: 3028...  Training loss: 0.9605...  6.4893 sec/batch
Epoch: 90/100...  Training Step: 3029...  Training loss: 0.9619...  5.9204 sec/batch
Epoch: 90/100...  Training Step: 3030...  Training loss: 0.9737...  5.8369 sec/batch
Epoch: 90/100...  Training Step: 3031...  Training loss: 0.9649...  5.8320 sec/batch
Epoch: 90/100...  Training Step: 3032...  Training loss: 0.9403...  5.8387 sec/batch
Epoch: 90/100...  Training Step: 3033...  Training loss: 0.9498...  5.8431 sec/batch
Epoch: 90/100...  Training Step: 3034...  Training loss: 0.9359..

Epoch: 92/100...  Training Step: 3120...  Training loss: 0.9423...  5.7924 sec/batch
Epoch: 92/100...  Training Step: 3121...  Training loss: 0.9296...  5.8122 sec/batch
Epoch: 92/100...  Training Step: 3122...  Training loss: 0.9242...  5.7858 sec/batch
Epoch: 92/100...  Training Step: 3123...  Training loss: 0.9383...  5.8078 sec/batch
Epoch: 92/100...  Training Step: 3124...  Training loss: 0.9361...  5.8706 sec/batch
Epoch: 92/100...  Training Step: 3125...  Training loss: 0.9349...  5.8408 sec/batch
Epoch: 92/100...  Training Step: 3126...  Training loss: 0.9619...  5.7559 sec/batch
Epoch: 92/100...  Training Step: 3127...  Training loss: 0.9715...  5.8675 sec/batch
Epoch: 92/100...  Training Step: 3128...  Training loss: 0.9219...  5.8439 sec/batch
Epoch: 93/100...  Training Step: 3129...  Training loss: 0.9887...  5.8547 sec/batch
Epoch: 93/100...  Training Step: 3130...  Training loss: 0.9420...  5.8479 sec/batch
Epoch: 93/100...  Training Step: 3131...  Training loss: 0.9395..

Epoch: 95/100...  Training Step: 3217...  Training loss: 0.9366...  6.1750 sec/batch
Epoch: 95/100...  Training Step: 3218...  Training loss: 0.9039...  5.8584 sec/batch
Epoch: 95/100...  Training Step: 3219...  Training loss: 0.9313...  6.3588 sec/batch
Epoch: 95/100...  Training Step: 3220...  Training loss: 0.9061...  6.1897 sec/batch
Epoch: 95/100...  Training Step: 3221...  Training loss: 0.9115...  7.4573 sec/batch
Epoch: 95/100...  Training Step: 3222...  Training loss: 0.9254...  7.1236 sec/batch
Epoch: 95/100...  Training Step: 3223...  Training loss: 0.9164...  5.9437 sec/batch
Epoch: 95/100...  Training Step: 3224...  Training loss: 0.9200...  5.9156 sec/batch
Epoch: 95/100...  Training Step: 3225...  Training loss: 0.9275...  6.3895 sec/batch
Epoch: 95/100...  Training Step: 3226...  Training loss: 0.9289...  6.0326 sec/batch
Epoch: 95/100...  Training Step: 3227...  Training loss: 0.9165...  5.9427 sec/batch
Epoch: 95/100...  Training Step: 3228...  Training loss: 0.9364..

Epoch: 98/100...  Training Step: 3314...  Training loss: 0.9092...  5.8712 sec/batch
Epoch: 98/100...  Training Step: 3315...  Training loss: 0.9184...  5.8310 sec/batch
Epoch: 98/100...  Training Step: 3316...  Training loss: 0.9075...  5.7916 sec/batch
Epoch: 98/100...  Training Step: 3317...  Training loss: 0.9011...  5.8268 sec/batch
Epoch: 98/100...  Training Step: 3318...  Training loss: 0.8984...  5.8120 sec/batch
Epoch: 98/100...  Training Step: 3319...  Training loss: 0.9194...  5.8835 sec/batch
Epoch: 98/100...  Training Step: 3320...  Training loss: 0.8894...  6.6018 sec/batch
Epoch: 98/100...  Training Step: 3321...  Training loss: 0.9052...  6.1160 sec/batch
Epoch: 98/100...  Training Step: 3322...  Training loss: 0.8880...  5.9560 sec/batch
Epoch: 98/100...  Training Step: 3323...  Training loss: 0.9015...  6.3555 sec/batch
Epoch: 98/100...  Training Step: 3324...  Training loss: 0.9069...  7.1419 sec/batch
Epoch: 98/100...  Training Step: 3325...  Training loss: 0.8919..

In [18]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints/i3400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i300_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i600_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i900_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1200_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1500_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i1800_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2100_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2400_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i2700_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3000_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3300_l512.ckpt"
all_model_checkpoint_paths: "checkpoints/i3400_l512.ckpt"

In [19]:
def select_characters(predictions, vocab_size, top = 5):
    probs = np.squeeze(predictions)
    probs[np.argsort(probs)[: -top]] = 0
    probs = probs / np.sum(probs)
    chars = np.random.choice(vocab_size, 1, p=probs)[0]
    return chars

In [20]:
def sample_and_select(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime] 
    
    # During sampling and selecting, we pass  one character at a time
    batch_size, num_steps = 1, 1
    num_layers = 2
    num_classes = len(vocab)
    learning_rate = 0.001  
    grad_clip = 5
    
    tf.reset_default_graph()

    ## Getting input tensors
    inputs, targets, keep_prob = placeholders(batch_size, num_steps)

    ## Creating LSTM Cell
    cell, initial_state = lstms(lstm_size, num_layers, batch_size, keep_prob)

    ## One hot encode inputs to run the data through RNN layers
    one_hot_inputs = tf.one_hot(inputs, num_classes)

    ## Collect outputs
    outputs, state = tf.nn.dynamic_rnn(cell, one_hot_inputs, initial_state = initial_state)
    final_state = state

    ## Predictions and Logits
    prediction, logits = rnn_output(outputs, lstm_size, num_classes)

    ## Getting losses and optimizer(ADAM)
    loss = losses(logits, targets, lstm_size, num_classes)
    optimizer = cal_optimizer(loss, learning_rate, grad_clip)

    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(initial_state)
        
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {inputs: x,
                    keep_prob: 1.,
                    initial_state: new_state}
            preds, new_state = sess.run([prediction, final_state], 
                                         feed_dict=feed)

        c = select_characters(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {inputs: x,
                    keep_prob: 1.,
                    initial_state: new_state}
            preds, new_state = sess.run([prediction, final_state], 
                                         feed_dict=feed)

            c = select_characters(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

In [21]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints/i3400_l512.ckpt'

# Sampling New Book Text Output

In [22]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample_and_select(checkpoint, 2000, lstm_size, len(vocab), prime='It was a ')
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i3400_l512.ckpt
It was a very lung on again. Harry's eyes was stulling forbidd out his wand. Harry shore he was looking for a broomstick like it. 

"What about a lot of the ends of the Stitch, Harry?" Harry asked. 

"Harry Potter," said Ron. "I suppose you ageed that this is it." 

"We were doing it with un calls about the nearest thes, tried to go to the Dursleys to go to bed, everyone expected a tice so was hin if you've did is brave with the way it with the same sandwiches, and that he had seven his indied in his parchment. Harry's broom and filled the crept back in the doorway, too, too. 

"What's that since thing I'm been in tho portrinir, they're not somewhere.'." 

He took a diffeent corridor she had seen anything that he was sure wearing a spark of bed of them, but Harry couldn't see him. He had bleak the door so him help up as the things toward the should be said. "We've got to get a pink of prefects for Gryffindor," said H

In [23]:
checkpoint = 'checkpoints/i3400_l512.ckpt'
samp = sample_and_select(checkpoint, 2000, lstm_size, len(vocab), prime="It was")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i3400_l512.ckpt
It was almost beding it in the stands out of the door. "All right, thanks, you." 

"You want to go on the forest, Professor --" 

"Dear, Professor Flitwick, can't be saying standing on together. So he couldn't feel thle out of the strange to see of her wind wish hig, troubling. What came of trying the library came and was through the door, but some night and seen that the one will rever bit of coming, troill the way at once. 

"Anyway to me showly in this face, she wen possibly knowing what the pall ce say something to a smout of secret, but he didn't know what was wolding agoon. He saw the shock, Professor McGonagall like a half and breaking. 

"Well, you say the teachers's brilliant in the ground -- an' the train for the Dursleys have need before ter get a great letter on the first. Harry Potter, who came to bed and walked up, back at his beard. "I haven't saw a hundred and father ain of tress." 

"They couldn't fi

In [24]:
checkpoint = 'checkpoints/i3000_l512.ckpt'
samp = sample_and_select(checkpoint, 2000, lstm_size, len(vocab), prime="It was")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i3000_l512.ckpt
It was another of them, his batorchase out of a second, breath as they climbed boraing through the train. 

"He saw you and whet you were streng?" he said. "An't you surp that, you could have been told a bin of moved books. He had a porteffil firch -- he was going to be will with the train. It was all over them. So they're nervous." 

"I know that miround you think they're surprise..." 

Harry was starting to fame as he waid for, teeling him. 

Harry stared at him, staring at him, back at Hermione and Harry how come, and when Harry had seen in his fiftern's news. 

"Well, I want to get past that any of you," said Hagrid cloply. It was almost spreated silver that bother. 

"I don't sheak to differentes that wouse thinking those ones and Slytherin to do anything on his fingers, that wish of her bedie a large toad. His badly fation. However, they'd go an' can't bed it in for her.." 

"Walking up, that's a sort of someth

In [25]:
checkpoint = 'checkpoints/i2700_l512.ckpt'
samp = sample_and_select(checkpoint, 2000, lstm_size, len(vocab), prime="It was")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i2700_l512.ckpt
It was a vaisting not beding when he'd been so they spent her happens. It was one of them at a stair of stanters back on the ground, and Harry thought a second holed by Harry could hear here about the four fating them something all over the other two of the table, he had so say of herpen to their listly with the stone stared at Hagrid. 

He would be so they look at him. He heard the train that should be a scaratte on the floor and shoutded all silver high. The shool half to see that Hagrid was so full of the throegh somet to sheek without a long rait supposed to go toward the wall, everyone was turning the trains of corridors hungred. 

"I shouldn't be a letter." 

"It's not bad in his poremet?" Hermione was taking him a last letter. He tried to threw her almost faces on her last with him and chumbled on him back to the library not terming to their lose back to stare. 

"Well, it's the sudden having a crubb -- what's